#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 26 14:20:51 2021

@author: mollygravett
"""

original_pdb_com = [134.69, 323.79, 45.72]
pdb_com_10 = [134.66, 318.70, 43.37]
pdb_com_15 = [129.49, 320.48, 41.59]
pdb_com_20 = [128.81, 312.11, 39.42]
pdb_com_30 = [118.80, 308.46, 39.84]

original_com = [50.50, 30.04, 33.41]
com_10 = [25.29, 14.58, 16.48]
com_15 = [16.39, 9.80, 10.77]
com_20 = [12.55, 6.97, 8.15]
com_30 = [7.23, 4.14, 5.03]

com_10_r = [50.49, 30.23, 33.37]
com_15_r = [49.15, 29.15, 32.42]
com_20_r = [50.59, 27.43, 32.96]
com_30_r = [44.41, 26.75, 31.06]


fit_10 = [2.83851107, 4.28512574, -0.00873423]
fit_15 = [4.38360788, 3.24927270, 3.73694810]
fit_20 = [8.21956693, 10.20092165, 3.70339135]
fit_30 = [17.43401119, 9.58864386, -5.33981698]

fit_10_in = [-2.46141904,  -4.40216286, -0.13557464]

original_origin = [-117.703995, 172.448, -120.83199]

diff_og_10 = []
for i in range(3):
    diff_og_10.append(original_pdb_com[i]-pdb_com_10[i])

expect_10 = []
for i in range(3):
    expect_10.append((5/10)*original_com[i])
    
p_e_10 = []
for i in range(3):
    p_e_10.append(expect_10[i]/com_10[i])
    
correction_p_10 = []
    
diff_og_20 = []
for i in range(3):
    diff_og_20.append(original_pdb_com[i]-pdb_com_20[i])
    
expect_20 = []
for i in range(3):
    expect_20.append((5/20)*original_com[i])
    
p_e_20 = []
for i in range(3):
    p_e_20.append(expect_20[i]/com_20[i])
    
diff_og_30 = []
for i in range(3):
    diff_og_30.append(original_pdb_com[i]-pdb_com_30[i])

expect_30 = []
for i in range(3):
    expect_30.append((5/30)*original_com[i])

p_e_30 = []
for i in range(3):
    p_e_30.append(com_30[i]/expect_30[i])

d_e_30 = []
for i in range(3):
    d_e_30.append(expect_30[i]-com_30[i])

correction_p_30 = []
for i in range(3):
    correction_p_30.append(p_e_30[i]*original_origin[i])

correction_d_30 = []
for i in range(3):
    correction_d_30.append(original_origin[i]+d_e_30[i])
    
correction_t_30 = []
for i in range(3):
    correction_t_30.append(original_origin[i]+fit_30[i])
    
p_e_30_r = []
for i in range(3):
    p_e_30_r.append((original_com[i]/com_30_r[i])*original_origin[i])
    
d_e_30_r = []
for i in range(3):
    d_e_30_r.append((original_com[i]-com_30_r[i])+original_origin[i])